### ISSUE TITLE
tempfile reference unbound when not converting gif

### ISSUE THREAD

**Issue by JamzumSum** [milkice233/efb-qq-plugin-mirai#2]
由于
https://github.com/milkice233/efb-qq-plugin-mirai/blob/c1953b88a77df343269a270019ec2f2e7622405b/efb_qq_plugin_mirai/mirai.py#L176
未指定对象而导致的
https://github.com/milkice233/efb-qq-plugin-mirai/blob/c1953b88a77df343269a270019ec2f2e7622405b/efb_qq_plugin_mirai/mirai.py#L218-L219
在执行未定义`f`的分支之后引用未定义对象；

简单地改为`f = None`即可解决. 

（有点懒得fork交PR 见谅）

**Comment by milkice233** [comment]
了解，感谢

**Comment by milkice233** [comment]
0444fb01254fd9a68880999e9330cdf7ed0ea248
